class OfficerAuth {
  final int authId;
  final int officerId;
  final String? codeHash; // This holds the random code generated by the officer
  final DateTime createdAt;
  final DateTime expiresAt;
  final DateTime? usedAt;
  final int? machineId;
  final AuthStatus status;

  OfficerAuth({
    required this.authId,
    required this.officerId,
    this.codeHash,
    required this.createdAt,
    required this.expiresAt,
    this.usedAt,
    this.machineId,
    required this.status,
  });

  factory OfficerAuth.fromJson(Map<String, dynamic> json) {
    return OfficerAuth(
      authId: json['auth_id'],
      officerId: json['officer_id'],
      codeHash: json['code_hash'],
      createdAt: json['created_at'] is String 
          ? DateTime.parse(json['created_at']) 
          : (json['created_at'] as dynamic).toDate(), // Safely handles Firebase Timestamps
      expiresAt: json['expires_at'] is String 
          ? DateTime.parse(json['expires_at']) 
          : (json['expires_at'] as dynamic).toDate(),
      usedAt: json['used_at'] != null 
          ? (json['used_at'] is String ? DateTime.parse(json['used_at']) : (json['used_at'] as dynamic).toDate())
          : null,
      machineId: json['machine_id'],
      status: AuthStatus.fromString(json['status']),
    );
  }
}

class OfficerAuthRequest {
  final String code;
  final int machineId;

  OfficerAuthRequest({
    required this.code,
    required this.machineId,
  });

  Map<String, dynamic> toJson() {
    return {
      'code': code,
      'machine_id': machineId,
    };
  }
}

class OfficerAuthResponse {
  final bool success;
  final String? sessionToken;
  final String? officerName;
  final String? message;

  OfficerAuthResponse({
    required this.success,
    this.sessionToken,
    this.officerName,
    this.message,
  });

  factory OfficerAuthResponse.fromJson(Map<String, dynamic> json) {
    return OfficerAuthResponse(
      success: json['success'] as bool? ?? false,
      sessionToken: json['session_token'] as String?,
      officerName: json['officer_name'] as String?,
      message: json['message'] as String?,
    );
  }
}

enum AuthStatus {
  active,
  used,
  expired;

  static AuthStatus fromString(String value) {
    switch (value) {
      case 'active':
        return AuthStatus.active;
      case 'used':
        return AuthStatus.used;
      case 'expired':
        return AuthStatus.expired;
      default:
        return AuthStatus.expired;
    }
  }
}